#!/bin/bash
set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="$DOTFILES_DIR/config.json"
OUT_DIR="$DOTFILES_DIR/config"
GITCONFIG_OUT="$OUT_DIR/.gitconfig"
GITIGNORE_OUT="$OUT_DIR/.gitignore_global"

mkdir -p "$OUT_DIR"

BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m'

info()    { echo -e "${BLUE}[gitconfig]${NC} $1"; }
success() { echo -e "${GREEN}[gitconfig]${NC} $1"; }

# ─── Read default account ─────────────────────────────────────────────────────
DEFAULT_ACCOUNT=$(jq -c '.git.accounts[] | select(.default == true)' "$CONFIG")
DEFAULT_NAME=$(echo "$DEFAULT_ACCOUNT"  | jq -r '.name')
DEFAULT_EMAIL=$(echo "$DEFAULT_ACCOUNT" | jq -r '.email')

info "Default git identity: $DEFAULT_NAME <$DEFAULT_EMAIL>"

# ─── Generate .gitconfig ──────────────────────────────────────────────────────
info "Generating $GITCONFIG_OUT..."

cat > "$GITCONFIG_OUT" << GITCONFIG
# ─────────────────────────────────────────────────────────────────────────────
# .gitconfig — AUTO-GENERATED by generate/gitconfig.sh
# DO NOT EDIT MANUALLY. Edit config.json and re-run: bash generate/gitconfig.sh
# ─────────────────────────────────────────────────────────────────────────────

[user]
  name  = $DEFAULT_NAME
  email = $DEFAULT_EMAIL

[core]
  editor          = code --wait
  excludesfile    = ~/.gitignore_global
  autocrlf        = input
  whitespace      = trailing-space,space-before-tab

[alias]
  st      = status
  co      = checkout
  br      = branch
  lg      = log --oneline --graph --decorate --all
  undo    = reset --soft HEAD~1
  aliases = config --get-regexp alias

[pull]
  rebase = false

[push]
  default = current

[init]
  defaultBranch = main

[color]
  ui = auto
GITCONFIG

success "Generated: $GITCONFIG_OUT"

# ─── Generate .gitignore_global ───────────────────────────────────────────────
info "Generating $GITIGNORE_OUT..."

cat > "$GITIGNORE_OUT" << GITIGNORE_HEADER
# ─────────────────────────────────────────────────────────────────────────────
# .gitignore_global — AUTO-GENERATED by generate/gitconfig.sh
# DO NOT EDIT MANUALLY. Edit config.json and re-run: bash generate/gitconfig.sh
# ─────────────────────────────────────────────────────────────────────────────

GITIGNORE_HEADER

jq -r '.gitignore_global[]' "$CONFIG" >> "$GITIGNORE_OUT"

success "Generated: $GITIGNORE_OUT"
