#!/bin/bash
set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="$DOTFILES_DIR/config.json"
OUT_DIR="$DOTFILES_DIR/config/.ssh"
OUT="$OUT_DIR/config"

mkdir -p "$OUT_DIR"
chmod 700 "$OUT_DIR"

BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m'

info()    { echo -e "${BLUE}[ssh_config]${NC} $1"; }
success() { echo -e "${GREEN}[ssh_config]${NC} $1"; }

info "Generating $OUT from config.json..."

cat > "$OUT" << 'SSH_HEADER'
# ─────────────────────────────────────────────────────────────────────────────
# ~/.ssh/config — AUTO-GENERATED by generate/ssh_config.sh
# DO NOT EDIT MANUALLY. Edit config.json and re-run: bash generate/ssh_config.sh
# ─────────────────────────────────────────────────────────────────────────────

SSH_HEADER

ACCOUNTS=$(jq -c '.git.accounts[]' "$CONFIG")

while IFS= read -r account; do
  HOST_ALIAS=$(echo "$account" | jq -r '.host_alias')
  KEY_NAME=$(echo "$account"   | jq -r '.key_name')
  NAME=$(echo "$account"       | jq -r '.name')

  cat >> "$OUT" << SSH_BLOCK
# Account: $NAME
Host $HOST_ALIAS
  HostName github.com
  User git
  AddKeysToAgent yes
  UseKeychain yes
  IdentityFile ~/.ssh/$KEY_NAME

SSH_BLOCK

done <<< "$ACCOUNTS"

chmod 600 "$OUT"
success "Generated: $OUT"
