#!/bin/bash
set -e

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
CONFIG="$DOTFILES_DIR/config.json"
OUT_DIR="$DOTFILES_DIR/config"
OUT="$OUT_DIR/.zshrc"

mkdir -p "$OUT_DIR"

BLUE='\033[0;34m'
GREEN='\033[0;32m'
NC='\033[0m'

info()    { echo -e "${BLUE}[zshrc]${NC} $1"; }
success() { echo -e "${GREEN}[zshrc]${NC} $1"; }

info "Generating $OUT from config.json..."

GCLOUD_ENABLED=$(jq -r '.gcloud.enabled' "$CONFIG")

# ─── Begin writing .zshrc ─────────────────────────────────────────────────────
cat > "$OUT" << 'ZSHRC_HEADER'
# ─────────────────────────────────────────────────────────────────────────────
# .zshrc — AUTO-GENERATED by generate/zshrc.sh
# DO NOT EDIT MANUALLY. Edit config.json and re-run: bash generate/zshrc.sh
# ─────────────────────────────────────────────────────────────────────────────

# ── Homebrew ──────────────────────────────────────────────────────────────────
eval "$(/opt/homebrew/bin/brew shellenv)"

# ── NVM (Node Version Manager) ────────────────────────────────────────────────
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"

# ── Pyenv ─────────────────────────────────────────────────────────────────────
export PYENV_ROOT="$HOME/.pyenv"
export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"

# ── Direnv ────────────────────────────────────────────────────────────────────
eval "$(direnv hook zsh)"

ZSHRC_HEADER

# ─── Gcloud (conditional) ─────────────────────────────────────────────────────
if [ "$GCLOUD_ENABLED" = "true" ]; then
cat >> "$OUT" << 'GCLOUD_BLOCK'
# ── Google Cloud SDK ──────────────────────────────────────────────────────────
source "$(brew --prefix)/share/google-cloud-sdk/path.zsh.inc"
source "$(brew --prefix)/share/google-cloud-sdk/completion.zsh.inc"

GCLOUD_BLOCK
fi

# ─── Git identity aliases ─────────────────────────────────────────────────────
echo "# ── Git identity aliases ─────────────────────────────────────────────────────" >> "$OUT"

ACCOUNTS=$(jq -c '.git.accounts[]' "$CONFIG")
while IFS= read -r account; do
  NAME=$(echo "$account"      | jq -r '.name')
  EMAIL=$(echo "$account"     | jq -r '.email')
  HOST_ALIAS=$(echo "$account"| jq -r '.host_alias')
  # Strip "github.com-" prefix for the alias shortname
  SHORT="${HOST_ALIAS#github.com-}"
  echo "alias git-${SHORT}='git config user.name \"${NAME}\" && git config user.email \"${EMAIL}\"'" >> "$OUT"
done <<< "$ACCOUNTS"

echo "" >> "$OUT"

# ─── Git aliases ──────────────────────────────────────────────────────────────
echo "# ── Git aliases ──────────────────────────────────────────────────────────────" >> "$OUT"

GIT_ALIASES=$(jq -r '.aliases.git | to_entries[] | "alias \(.key)=\u0027\(.value)\u0027"' "$CONFIG")
echo "$GIT_ALIASES" >> "$OUT"
echo "" >> "$OUT"

# ─── Shell aliases ────────────────────────────────────────────────────────────
echo "# ── Shell aliases ────────────────────────────────────────────────────────────" >> "$OUT"

SHELL_ALIASES=$(jq -r '.aliases.shell | to_entries[] | "alias \(.key)=\u0027\(.value)\u0027"' "$CONFIG")
echo "$SHELL_ALIASES" >> "$OUT"
echo "" >> "$OUT"

# ─── Custom aliases ───────────────────────────────────────────────────────────
CUSTOM_COUNT=$(jq '.aliases.custom | length' "$CONFIG")
if [ "$CUSTOM_COUNT" -gt 0 ]; then
  echo "# ── Custom aliases ───────────────────────────────────────────────────────────" >> "$OUT"
  CUSTOM_ALIASES=$(jq -r '.aliases.custom | to_entries[] | "alias \(.key)=\u0027\(.value)\u0027"' "$CONFIG")
  echo "$CUSTOM_ALIASES" >> "$OUT"
  echo "" >> "$OUT"
fi

# ─── Git identity function + prompt ───────────────────────────────────────────
cat >> "$OUT" << 'PROMPT_BLOCK'
# ── Git identity helper ───────────────────────────────────────────────────────
function git_identity() {
  local email
  email=$(git config user.email 2>/dev/null)
  [ -n "$email" ] && echo " ($email)"
}

# ── Git branch helper ─────────────────────────────────────────────────────────
function git_branch() {
  local branch
  branch=$(git symbolic-ref --short HEAD 2>/dev/null)
  [ -n "$branch" ] && echo " ($branch)"
}

# ── Custom prompt ─────────────────────────────────────────────────────────────
# Format: dir (branch) [email] %
setopt PROMPT_SUBST
PROMPT='%F{cyan}%~%f%F{yellow}$(git_branch)%f%F{green}$(git_identity)%f %F{white}%%%f '

# ── fzf ───────────────────────────────────────────────────────────────────────
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
PROMPT_BLOCK

success "Generated: $OUT"
